[package]
name = "terminput-uefi"
version = "0.1.0"
description = "terminput implementation for UEFI"
readme.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true

[dependencies]
terminput.workspace = true
uefi.workspace = true
